apiVersion: v1
kind: Service
metadata:
    name: "demo-66d2"
    labels:
        app: "demo-66d2"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "demo-66d2"