apiVersion: v1
kind: Service
metadata:
    name: "demo-43d3"
    labels:
        app: "demo-43d3"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "demo-43d3"